- hosts: localhost
  tasks:
    - name: PutManagementGroup
      azure.rm.managementgroup:
        group_id: ChildGroup
        id: /providers/Microsoft.Management/managementGroups/ChildGroup
        type: /providers/Microsoft.Management/managementGroups/
        name: ChildGroup
        properties:
          tenant_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
          display_name: ChildGroup
          details:
            parent:
              id: /providers/Microsoft.Management/managementGroups/RootGroup
    - name: AddSubscriptionToManagementGroup
      azure.rm.managementgroupsubscription:
        group_id: myManagementGroup
    - name: Create Subscription
      azure.rm.subscriptionfactory:
        enrollment_account_name: myEnrollmentAccount
        body:
          offerType: MS-AZR-0017P
          displayName: Test Ea Azure Sub
          owners:
            - objectId: 973034ff-acb7-409c-b731-e789672c7b31
            - objectId: 67439a9e-8519-4016-a630-f5f805eba567
          additionalParameters:
            customData:
              key1: value1
              key2: true