namespace: "azure"
name: "rm"
version: "0.0.5"
readme: "README.md"
authors:
    - "Liu Qingyi"
license:
    - "MIT"
tags:
    - demo
    - collection
repository: "https://github.com/Azure/AnsibleCollection"
